# GitHub Actions only runs on pull requests.
# 1. Check out the code in the pull request
# 2. Use Lintly-Flake8 by passing the GitHub Actions bot token --> ensures that the bot github-actions will be used for the review
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
